version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  db: 
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes: 
    - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

