version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    networks: 
      - node-network
    volumes:
      - ./node/src:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    #entrypoint: wait-for app:3000 -t 40 -- /docker-entrypoint.sh && service nginx start
    networks: 
      - node-network
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - app

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
    - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
